project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: false

website:
  title: "Sci Comp Workshop - GitHub"
  favicon: images/logos/scicomptools_hex.png
  repo-url: https://github.com/NCEAS/scicomp-workshop-collaborative-coding
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home"
      - text: "Core Topics"
        menu:
          - motivations.qmd
          - github.qmd
          - rstudio.qmd
      - text: "Advanced Topics"
        menu: 
          - conflicts.qmd
          - branches.qmd
          - forks.qmd
      - text: "Project Management"
        menu: 
          - issues.qmd
      - server.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/NCEAS/scicomp-workshop-collaborative-coding
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer: |
    <img src="images/logos/nceas_logo_square.png" width="40%"/>
    <img src="images/logos/lter_logo_square.png" width="40%"/>

format:
  html:
    theme:
       light: yeti
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    