project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: false

website:
  title: "NCEAS Sci Comp Workshop - GitHub"
  favicon: images/scicomptools_hex.png
  repo-url: https://nceas.github.io/scicomp-workshop-collaborative-coding/
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - content.qmd
      - about.qmd
    right:
      - icon: github
        href: https://nceas.github.io/scicomp-workshop-collaborative-coding/
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary

format:
  html:
    theme:
       light: yeti
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    