project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: false

website:
  title: "Sci Comp Workshop - Collaborative Coding with GitHub"
  favicon: images/logos/scicomptools_hex.png
  repo-url: https://github.com/NCEAS/scicomp-workshop-collaborative-coding
  repo-actions: [issue]
  twitter-card: true
  sidebar:
    style: "docked"
    background: secondary
    search: true
    contents: 
      - text: "Workshop Home"
        href: index.qmd
      - section: "Core Topics"
        contents:
          - motivations.qmd
          - github.qmd
          - rstudio.qmd
      - section: "Advanced Topics"
        contents: 
          - conflicts.qmd
          - branches.qmd
          - forks.qmd
      - section: "Project Management"
        contents: 
          - issues.qmd
          - projects.qmd
          - readmes.qmd
      - server.qmd
  navbar:
    background: primary
    right:
      - text: "Sci Comp Team"
        menu:
          - href: https://nceas.github.io/scicomp.github.io/
            text: "Home"
          - href: https://nceas.github.io/scicomp.github.io/staff.html
            text: "People"
      - text: "Other Workshops"
        menu:
          - href: https://nceas.github.io/scicomp-workshop-collaborative-coding/
            text: "GitHub"
          - href: https://nceas.github.io/scicomp-workshop-tidyverse/
            text: "Tidyverse"
          - href: https://njlyon0.github.io/asm-2022_shiny-workshop/
            text: "R Shiny"
      - icon: github
        href: https://github.com/NCEAS/scicomp-workshop-collaborative-coding
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer: |
    <img src="images/logos/nceas_logo_square.png" width="40%"/>
    <img src="images/logos/lter_logo_square.png" width="40%"/>

format:
  html:
    theme:
       light: scicomplight.scss
       dark: scicompdark.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    